<?xml version="1.0" encoding="UTF-8" ?>
<!-- 声明内部DTD -->
<!DOCTYPE books [
        <!ELEMENT books (book+) >
        <!ELEMENT book (name,author,price) >
        <!ATTLIST book id CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA) >
        <!ELEMENT author (#PCDATA) >
        <!ELEMENT price (#PCDATA) >
        ]>
<books>
    <book id="b001">
        <name>JavaEE高级编程</name>
        <author>王五</author>
        <price>78.00</price>
    </book>
    <book id="b002">
        <name>Java并发编程的艺术</name>
        <author>方腾飞</author>
        <price>57.00</price>
    </book>
</books>